version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: sync+restart
          path: ./public
          target: /usr/src/app/public
    restart: always
    command: bun run dev

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo-data:/data/db
