version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/bmx-stack
      - PORT=3000
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo-data:/data/db
